# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_auto_20160403_0034'),
        ('poem', '0004_auto_20160402_2157'),
    ]

    operations = [
    ]
