# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(b'article', b'article'), (b'noun', b'noun'), (b'verb', b'verb'), (b'adjective', b'adjective'), (b'adverb', b'adverb'), (b'preposition', b'preposition'), (b'conjunction', b'conjunction'), (b'pronoun', b'pronoun')], max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
